# Generated by Django 3.0.5 on 2020-12-29 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=150)),
                ('licence', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='email',
        ),
    ]
