# Generated by Django 3.0.5 on 2020-12-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201229_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_doctor',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as doctor.', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_patient',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as patient.', verbose_name='Patient'),
        ),
    ]
